### ISSUE TITLE
Triggering error around nokogiri and libxml incompatibility

### ISSUE THREAD

**Issue by amosshapira** [phinze/vagrant-host-shell#11]
My environment:
OS X Yosemite 10.10.3
Vagrant 1.7.2 (installed from the .dmg package)
vagrant-host-shell 0.0.4 installed using `vagrant plugin install vagrant-host-shell`
Using VirtualBox

Configuration:
```ruby
config.vm.provision :host_shell do |host_shell|
  host_shell.inline = 'rspec specs/all_spec.rb'
end
```

Command and error message:
```bash
$ vagrant provision --provision-with=host_shell all
==> all: Running provisioner: host_shell...
[stderr] /opt/vagrant/embedded/gems/gems/nokogiri-1.6.3.1/lib/nokogiri.rb:29:in `require': dlopen(/opt/vagrant/embedded/gems/gems/nokogiri-1.6.3.1/lib/nokogiri/nokogiri.bundle, 9): Library not loaded: @rpath/libxml2.dylib (LoadError)
  Referenced from: /opt/vagrant/embedded/gems/gems/nokogiri-1.6.3.1/lib/nokogiri/nokogiri.bundle
  Reason: Incompatible library version: nokogiri.bundle requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0 - /opt/vagrant/embedded/gems/gems/nokogiri-1.6.3.1/lib/nokogiri/nokogiri.bundle
	from /opt/vagrant/embedded/gems/gems/nokogiri-1.6.3.1/lib/nokogiri.rb:29:in `rescue in <top (required)>'
	from /opt/vagrant/embedded/gems/gems/nokogiri-1.6.3.1/lib/nokogiri.rb:25:in `<top (required)>'
	from /Users/amos.shapira/.vagrant.d/gems/gems/capybara-2.4.4/lib/capybara.rb:2:in `require'
	from /Users/amos.shapira/.vagrant.d/gems/gems/capybara-2.4.4/lib/capybara.rb:2:in `<top (required)>'
	from /Users/amos.shapira/.vagrant.d/gems/gems/infrataster-0.3.0/lib/infrataster/contexts/capybara_context.rb:1:in `require'
	from /Users/amos.shapira/.vagrant.d/gems/gems/infrataster-0.3.0/lib/infrataster/contexts/capybara_context.rb:1:in `<top (required)>'
	from /Users/amos.shapira/.vagrant.d/gems/gems/infrataster-0.3.0/lib/infrataster/contexts.rb:5:in `require'
	from /Users/amos.shapira/.vagrant.d/gems/gems/infrataster-0.3.0/lib/infrataster/contexts.rb:5:in `<top (required)>'
	from /Users/amos.shapira/.vagrant.d/gems/gems/infrataster-0.3.0/lib/infrataster.rb:5:in `require'
	from /Users/amos.shapira/.vagrant.d/gems/gems/infrataster-0.3.0/lib/infrataster.rb:5:in `<top (required)>'
	from /Users/amos.shapira/.vagrant.d/gems/gems/infrataster-0.3.0/lib/infrataster/rspec.rb:1:in `require'
	from /Users/amos.shapira/.vagrant.d/gems/gems/infrataster-0.3.0/lib/infrataster/rspec.rb:1:in `<top (required)>'
	from /Users/amos.shapira/Documents/configuration/specs/spec_helper.rb:1:in `require'
	from /Users/amos.shapira/Documents/configuration/specs/spec_helper.rb:1:in `<top (required)>'
	from /Users/amos.shapira/Documents/configuration/specs/all_spec.rb:1:in `require'
	from /Users/amos.shapira/Documents/configuration/specs/all_spec.rb:1:in `<top (required)>'
	from /Users/amos.shapira/.vagrant.d/gems/gems/rspec-core-3.3.1/lib/rspec/core/configuration.rb:1327:in `load'
	from /Users/amos.shapira/.vagrant.d/gems/gems/rspec-core-3.3.1/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
	from /Users/amos.shapira/.vagrant.d/gems/gems/rspec-core-3.3.1/lib/rspec/core/configuration.rb:1325:in `each'
	from /Users/amos.shapira/.vagrant.d/gems/gems/rspec-core-3.3.1/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
	from /Users/amos.shapira/.vagrant.d/gems/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:102:in `setup'
	from /Users/amos.shapira/.vagrant.d/gems/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:88:in `run'
	from /Users/amos.shapira/.vagrant.d/gems/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:73:in `run'
	from /Users/amos.shapira/.vagrant.d/gems/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/amos.shapira/.vagrant.d/gems/gems/rspec-core-3.3.1/exe/rspec:4:in `<top (required)>'
	from /usr/bin/rspec:23:in `load'
	from /usr/bin/rspec:23:in `<main>'
```
Other provisioners don't have an issue running.
The only Google search result for this error message is this Vagrant issue from a year ago: https://github.com/mitchellh/vagrant/issues/3794
I'm not sure it's relevant (it relates more about plugin installation issues), and so far following the voodoo steps suggested there didn't help.

**Comment by amosshapira** [comment]
Closing. When I changed the "rspec" command to a simple "echo" it succeeded, so the issue is not with the plugin but with rspec.
